### PR TITLE
Estimated reading time && fix #41

### LINKED ISSUE #41: Leancloud stats on homepage all show 0
I'm using the latest HEAD `5f88b3a`

Leancloud stats DO show the correct numbers for each article on its own page. But on the home page, all stats are showing as 0. Think it's related to a recent commit, but can't find it easily for now.

### PR DESCRIPTION
**Pull request by WangQiru**
Add "Estimated reading time" to .other-wrapper in post layout.
Didn't touch CSS though.

### CODE REVIEW

**Comment by WangQiru** [comment]
Need to figure out a way to exclude `<pre>` tag though

**Comment by kitian616** [comment]
Great Job! but I still have a question. 

the reading time seems too large. for example, I don't think [TeXt - Mermaid](https://tianqi.name/jekyll-TeXt-theme/test/2017/06/06/mermaid.html) really need  14 mins to read.

**Comment by WangQiru** [comment]
That’s what I mean to find a way for excluding tags like `<pre>`

**Comment by kitian616** [comment]
No, I mean this:
```
{% assign count = post.content | strip_html | strip_newlines | size %}
{% if count < 400 %}
  1 min to read
  {% else %}
  {{ count | divided_by:200 }} mins to read
{% endif %}
```
the `count` is the  **number of characters** in the content. and then you divided count by 200, witch means the reading speed is **200 characters per minute**.

**Comment by WangQiru** [comment]
I tested mine is 279 😂

My blog has some posts that take 50+ mins to read, due to `pre` tags.

**Comment by kitian616** [comment]
It 's number of words, but `count` is the number of characters. eg:
> I believe I can fly.
5 words, 20 characters

**Comment by WangQiru** [comment]
查了一下午的确没有很好的解决办法，尤其是多语言混合，jekyll 比 WordPress 还心累啊！

可能可以用 https://github.com/jpatokal/script_detector 或者自己造个轮子。。。

相关：
http://taoalpha.github.io/blog/2015/05/21/tech-jekyll-count-of-chinese-characters/
https://github.com/jekyll/jekyll/issues/1921
https://github.com/Shopify/liquid/issues/984

**Comment by kitian616** [comment]
在我看来，统计的结果可以不准确。但也应该在**偏小**的合理范围内，这样才能吸引访问者点击链接去看文章。（太长不看我是深有感触的）

**Pull request closed without merging**
