### PR TITLE
add korean locale

### PR DESCRIPTION
**Pull request by ssosso**
First of all, thank you to make this theme.
I added a locale so that it support Korean.
Please take a look at the source and approve pr:)
Thank you.

### CODE REVIEW

**Comment by kitian616** [comment]
Thank you!
So could you tell me how to say "hello" in Korean?

image

**Comment by ssosso** [comment]
@kitian616 

Thank you to ask me about Korean ˘◡˘ .
"Hello", "Hi" is.. you can say "안녕?([IPA](https://zh.wikipedia.org/wiki/%E5%9C%8B%E9%9A%9B%E9%9F%B3%E6%A8%99) : a̠nɲjʌ̹ŋ / 詞源: 安寧)" in Korean.
Also you can say "안녕하세요([IPA](https://zh.wikipedia.org/wiki/%E5%9C%8B%E9%9A%9B%E9%9F%B3%E6%A8%99) : a̠nɲjʌ̹ŋɦa̠sʰe̞jo / 詞源: 安寧 + 禮貌的表達: 하세요" when you speak more politely.

And I translated the word "Home" as you requested 👍 .
Thank you so much, friend.

**Comment by ssosso** [comment]
@kitian616 
Also if you need more Korean translation, you can leave an issue [here](https://github.com/ssosso/Docs-Reference-Translation/issues).
I will help you translate Korean.

**Comment by kitian616** [comment]
https://tianqi.name/jekyll-TeXt-theme/samples.html#languages

I made some update for locale(i18n).

**Comment by ssosso** [comment]
@kitian616 
Sorry, some minutes ago, I changed 'Subscribe' locale.
Please change "등록" -> "구독하기".

**Comment by kitian616** [comment]
I added 2 locale strings  "FOLLOW_US" and "EMAIL_US" at ae015c2635724220e07cfaba8bca67729a8d23b6.

Do you have time to translate them to Korean?

**Pull request merged**
